class Svatky:
    def kdo_ma_svatek(self, den):
        seznam = self.seznam_svatku()

        if den in seznam:
            return seznam[den]
        else:
            return "Neplatné číslo dne"

    def seznam_svatku(self):
        return {
            1: "|Nový rok|Státní svátek|Den obnovy samostatného českého státu",
            2: "Karina",
            3: "Radmila",
            4: "Diana",
            5: "Dalimil",
            6: "Kašpar, Melichar a Baltazar|Tři králové",
            7: "Vilma",
            8: "Čestmír",
            9: "Vladan",
            10: "Břetislav",
            11: "Bohdana",
            12: "Pravoslav",
            13: "Edita",
            14: "Radovan",
            15: "Alice",
            16: "Ctirad",
            17: "Drahoslav",
            18: "Vladislav",
            19: "Doubravka",
            20: "Ilona",
            21: "Běla",
            22: "Slavomír",
            23: "Zdeněk",
            24: "Milena",
            25: "Miloš",
            26: "Zora",
            27: "Ingrid",
            28: "Otýlie",
            29: "Zdislava",
            30: "Robin",
            31: "Marika",
            32: "Hynek",
            33: "Nela|Hromnice",
            34: "Blažej",
            35: "Jarmila",
            36: "Dobromila",
            37: "Vanda",
            38: "Veronika",
            39: "Milada",
            40: "Apolena",
            41: "Mojmír",
            42: "Božena",
            43: "Slavěna",
            44: "Věnceslav",
            45: "Valentýn",
            46: "Jiřina",
            47: "Ljuba",
            48: "Miloslava",
            49: "Gizela",
            50: "Patrik",
            51: "Oldřich",
            52: "Lenka",
            53: "Petr",
            54: "Svatopluk",
            55: "Matěj",
            56: "Liliana",
            57: "Dora, Dorota",
            58: "Alexandr",
            59: "Lumír",
            60: "Bedřich",
            61: "Anežka",
            62: "Kamil",
            63: "Stela",
            64: "Kazimír",
            65: "Miroslav",
            66: "Tomáš",
            67: "Gabriela",
            68: "Františka",
            69: "Viktorie",
            70: "Anděla",
            71: "Řehoř|Den přijetí ČR do NATO",
            72: "Růžena",
            73: "Rút, Matylda",
            74: "Ida",
            75: "Elena, Herbert",
            76: "Vlastimil",
            77: "Eduard",
            78: "Josef",
            79: "Světlana",
            80: "Radek",
            81: "Leona",
            82: "Ivona",
            83: "Gabriel",
            84: "Marián",
            85: "Emanuel",
            86: "Dita|Neděle velikonoční",
            87: "Soňa|Pondělí velikonoční",
            88: "Taťána",
            89: "Arnošt",
            90: "Kvido",
            91: "Hugo",
            92: "Erika",
            93: "Richard",
            94: "Ivana",
            95: "Miroslava",
            96: "Vendula",
            97: "Heřman, Hermína",
            98: "Ema",
            99: "Dušan",
            100: "Darja",
            101: "Izabela",
            102: "Julius",
            103: "Aleš",
            104: "Vincenc",
            105: "Anastázie",
            106: "Irena",
            107: "Rudolf",
            108: "Valérie",
            109: "Rostislav",
            110: "Marcela",
            111: "Alexandra",
            112: "Evženie",
            113: "Vojtěch",
            114: "Jiří",
            115: "Marek",
            116: "Oto",
            117: "Jaroslav",
            118: "Vlastislav",
            119: "Robert",
            120: "Blahoslav",
            121: "|Svátek práce",
            122: "Zikmund",
            123: "Alexej",
            124: "Květoslav",
            125: "Klaudie|Květnové povstání českého lidu",
            126: "Radoslav",
            127: "Stanislav",
            128: "|Den matek|Státní svátek|Den osvobození od fašismu",
            129: "Ctibor",
            130: "Blažena",
            131: "Svatava",
            132: "Pankrác",
            133: "Servác",
            134: "Bonifác",
            135: "Žofie",
            136: "Přemysl",
            137: "Aneta",
            138: "Nataša",
            139: "Ivo",
            140: "Zbyšek",
            141: "Monika",
            142: "Emil",
            143: "Vladimír",
            144: "Jana",
            145: "Viola",
            146: "Filip",
            147: "Valdemar",
            148: "Vilém",
            149: "Maxim, Maxmilián",
            150: "Ferdinand",
            151: "Kamila",
            152: "Laura",
            153: "Jarmil",
            154: "Tamara",
            155: "Dalibor",
            156: "Dobroslav",
            157: "Norbert",
            158: "Iveta, Slavoj",
            159: "Medard",
            160: "Stanislava",
            161: "Gita",
            162: "Bruno",
            163: "Antonie",
            164: "Antonín",
            165: "Roland",
            166: "Vít",
            167: "Zbyněk",
            168: "Adolf",
            169: "Milan",
            170: "Leoš",
            171: "Květa",
            172: "Alois",
            173: "Pavla",
            174: "Zdeňka",
            175: "Jan",
            176: "Ivan",
            177: "Adriana",
            178: "Ladislav",
            179: "Lubomír",
            180: "Petr a Pavel",
            181: "Šárka",
            182: "Jaroslava",
            183: "Patricie",
            184: "Radomír",
            185: "Prokop",
            186: "Cyril a Metoděj|Státní svátek|Den slovanských věrozvěstů Cyrila a Metoděje",
            187: "|Státní svátek|Den upálení mistra Jana Husa",
            188: "Bohuslava",
            189: "Nora",
            190: "Drahoslava",
            191: "Libuše, Amálie",
            192: "Olga",
            193: "Bořek",
            194: "Markéta",
            195: "Karolína",
            196: "Jindřich",
            197: "Luboš",
            198: "Martina",
            199: "Drahomíra",
            200: "Čeněk",
            201: "Ilja",
            202: "Vítězslav",
            203: "Magdaléna",
            204: "Libor",
            205: "Kristýna",
            206: "Jakub",
            207: "Anna",
            208: "Věroslav",
            209: "Viktor",
            210: "Marta",
            211: "Bořivoj",
            212: "Ignác",
            213: "Oskar",
            214: "Gustav",
            215: "Miluše",
            216: "Dominik",
            217: "Kristián",
            218: "Oldřiška",
            219: "Lada",
            220: "Soběslav",
            221: "Roman",
            222: "Vavřinec",
            223: "Zuzana",
            224: "Klára",
            225: "Alena",
            226: "Alan",
            227: "Hana",
            228: "Jáchym",
            229: "Petra",
            230: "Helena",
            231: "Ludvík",
            232: "Bernard",
            233: "Johana",
            234: "Bohuslav",
            235: "Sandra",
            236: "Bartoloměj",
            237: "Radim",
            238: "Luděk",
            239: "Otakar",
            240: "Augustýn",
            241: "Evelína",
            242: "Vladěna",
            243: "Pavlína",
            244: "Linda, Samuel",
            245: "Adéla",
            246: "Bronislav",
            247: "Jindřiška",
            248: "Boris",
            249: "Boleslav",
            250: "Regína",
            251: "Mariana",
            252: "Daniela",
            253: "Irma",
            254: "Denisa",
            255: "Marie",
            256: "Lubor",
            257: "Radka",
            258: "Jolana",
            259: "Ludmila",
            260: "Naděžda",
            261: "Kryštof",
            262: "Zita",
            263: "Oleg",
            264: "Matouš",
            265: "Darina",
            266: "Berta",
            267: "Jaromír",
            268: "Zlata",
            269: "Andrea",
            270: "Jonáš",
            271: "Václav|Státní svátek|Den české státnosti",
            272: "Michal",
            273: "Jeroným",
            274: "Igor",
            275: "Galina, Olívie, Oliver",
            276: "Bohumil",
            277: "František",
            278: "Eliška",
            279: "Hanuš",
            280: "Sergej, Justýna",
            281: "Věra",
            282: "Štefan, Sára",
            283: "Marina",
            284: "Andrej",
            285: "Marcel",
            286: "Renáta",
            287: "Agáta",
            288: "Tereza",
            289: "Havel",
            290: "Hedvika",
            291: "Lukáš",
            292: "Michaela",
            293: "Vendelín",
            294: "Brigita",
            295: "Sabina",
            296: "Teodor",
            297: "Nina",
            298: "Beáta",
            299: "Erik",
            300: "Zoja, Šarlota, Zoe",
            301: "|Státní svátek|Den vzniku samostatného československého státu",
            302: "Silvie",
            303: "Tadeáš",
            304: "Štěpánka",
            305: "Felix",
            306: "|Památka zesnulých",
            307: "Hubert",
            308: "Karel",
            309: "Miriam",
            310: "Liběna",
            311: "Saskie",
            312: "Bohumír",
            313: "Bohdan",
            314: "Evžen",
            315: "Martin",
            316: "Benedikt",
            317: "Tibor",
            318: "Sáva",
            319: "Leopold",
            320: "Otmar",
            321: "Mahulena|Státní svátek|Den boje za svobodu a demokracii",
            322: "Romana",
            323: "Alžběta",
            324: "Nikola",
            325: "Albert",
            326: "Cecílie",
            327: "Klement",
            328: "Emílie",
            329: "Kateřina",
            330: "Artur",
            331: "Xenie",
            332: "René",
            333: "Zina",
            334: "Ondřej",
            335: "Iva",
            336: "Blanka",
            337: "Svatoslav",
            338: "Barbora",
            339: "Jitka",
            340: "Mikuláš",
            341: "Ambrož, Benjamín",
            342: "Květoslava",
            343: "Vratislav",
            344: "Julie",
            345: "Dana",
            346: "Simona",
            347: "Lucie",
            348: "Lýdie",
            349: "Radana, Radan",
            350: "Albína",
            351: "Daniel",
            352: "Miloslav",
            353: "Ester",
            354: "Dagmar",
            355: "Natálie",
            356: "Šimon",
            357: "Vlasta",
            358: "Adam a Eva|Štědrý den",
            359: "|1. svátek vánoční|Boží hod vánoční",
            360: "Štěpán|2. svátek vánoční",
            361: "Žaneta",
            362: "Bohumila",
            363: "Judita",
            364: "David",
            365: "Silvestr"
        }